project_id: "324607"
api_token_env: LAMETA_CROWDIN_TOKEN
preserve_hierarchy: false # we don't want to see the "en/messages.po", just "messages.po"
base_path: "./locale"
files:
  [
    {
      "source": /en/messages.po,
      "translation": /%two_letters_code%/messages.po,
    },
    {
      "source": /*.csv,
      "translation": /%original_file_name%,
      "first_line_contains_header": true,
      "scheme": "identifier,source_phrase,context,uk,ru,fr",
    },
  ]
